<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="3.0">
    <xsl:output method="xml" indent="yes"/>
    <xsl:template match="/">
        <Invoice>
            <Items>
                <xsl:for-each select="/X12_850/PO1Loop">
                    <Item>
                        <Number>
                            <xsl:value-of select="PO1/PO1-01"/>
                        </Number>
                    </Item>
                </xsl:for-each>
            </Items>
        </Invoice>
    </xsl:template>
</xsl:stylesheet>
