<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:fn="http://www.w3.org/2005/xpath-functions">
    <xsl:output method="text" indent="yes" />

    <xsl:param name="Cart" />
    <xsl:param name="OrderSequence" />
    <xsl:param name="Account" />

    <!-- Step1: Converts JSON inputs to lossless XML -->
    <xsl:variable
            name="Cart-x" select="json-to-xml($Cart)" />
    <xsl:variable
            name="Account-x" select="json-to-xml($Account)" />

    <!-- Step2: Pre-process data mappings to lossless XML -->
    <!--
      Use lossless XML structure for both sources and target
    -->
    <xsl:variable name="mapped-xml">
        <fn:map>
            <fn:string key="OrderId"><xsl:value-of select="upper-case(concat('ORD-', $Account-x/fn:map/fn:string[@key='AccountId'], '-', $OrderSequence))"/></fn:string>
            <fn:string key="OrderPerson"><xsl:value-of select="$Account-x/fn:map/fn:string[@key='AccountId'], ':', $Account-x/fn:map/fn:string[@key='Name']"/></fn:string>
            <fn:map key="ShipTo">
                <fn:string key="Name"><xsl:value-of select="$Account-x/fn:map/fn:string[@key='Name']"/></fn:string>
                <fn:string key="Street"><xsl:value-of select="$Account-x/fn:map/fn:map[@key='Address']/fn:string[@key='Street']"/></fn:string>
                <fn:string key="City"><xsl:value-of select="$Account-x/fn:map/fn:map[@key='Address']/fn:string[@key='City']"/></fn:string>
                <fn:string key="State"><xsl:value-of select="$Account-x/fn:map/fn:map[@key='Address']/fn:string[@key='State']"/></fn:string>
                <fn:string key="Country"><xsl:value-of select="$Account-x/fn:map/fn:map[@key='Address']/fn:string[@key='Country']"/></fn:string>
            </fn:map>
            <fn:array key="Item">
                <xsl:for-each select="$Cart-x/fn:array/fn:map">
                    <fn:map>
                        <fn:string key="Title"><xsl:value-of select="fn:string[@key='Title']"/></fn:string>
                        <fn:number key="Quantity"><xsl:value-of select="fn:number[@key='Quantity']"/></fn:number>
                        <fn:number key="Price"><xsl:value-of select="fn:number[@key='Price']"/></fn:number>
                    </fn:map>
                </xsl:for-each>
            </fn:array>
        </fn:map>
    </xsl:variable>

    <!-- Step4: Converts lossless XML to JSON output -->
    <xsl:template match="/">
        <xsl:value-of select="xml-to-json($mapped-xml)" />
    </xsl:template>

</xsl:stylesheet>