<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xf="http://www.w3.org/2005/xpath-functions">
    <xsl:output method="text" indent="yes" />

    <xsl:param name="Cart" />
    <xsl:param name="OrderSequence" />
    <xsl:param name="Account" />

    <!-- Step1: Converts JSON inputs to lossless XML -->
    <xsl:variable
            name="Cart-x" select="json-to-xml($Cart)" />
    <xsl:variable
            name="Account-x" select="json-to-xml($Account)" />

    <!-- Step2: Pre-process data mappings to lossless XML -->
    <!--
      Use lossless XML structure for both sources and target
    -->
    <xsl:variable name="mapped-xml">
        <xf:map>
            <xf:string key="OrderId"><xsl:value-of select="upper-case(concat('ORD-', $Account-x/xf:map/xf:string[@key='AccountId'], '-', $OrderSequence))"/></xf:string>
            <xf:string key="OrderPerson"><xsl:value-of select="$Account-x/xf:map/xf:string[@key='AccountId'], ':', $Account-x/xf:map/xf:string[@key='Name']"/></xf:string>
            <xf:map key="ShipTo">
                <xf:string key="Name"><xsl:value-of select="$Account-x/xf:map/xf:string[@key='Name']"/></xf:string>
                <xf:string key="Street"><xsl:value-of select="$Account-x/xf:map/xf:map[@key='Address']/xf:string[@key='Street']"/></xf:string>
                <xf:string key="City"><xsl:value-of select="$Account-x/xf:map/xf:map[@key='Address']/xf:string[@key='City']"/></xf:string>
                <xf:string key="State"><xsl:value-of select="$Account-x/xf:map/xf:map[@key='Address']/xf:string[@key='State']"/></xf:string>
                <xf:string key="Country"><xsl:value-of select="$Account-x/xf:map/xf:map[@key='Address']/xf:string[@key='Country']"/></xf:string>
            </xf:map>
            <xf:array key="Item">
                <xsl:for-each select="$Cart-x/xf:array/xf:map">
                    <xf:map>
                        <xf:string key="Title"><xsl:value-of select="xf:string[@key='Title']"/></xf:string>
                        <xf:number key="Quantity"><xsl:value-of select="xf:number[@key='Quantity']"/></xf:number>
                        <xf:number key="Price"><xsl:value-of select="xf:number[@key='Price']"/></xf:number>
                    </xf:map>
                </xsl:for-each>
            </xf:array>
        </xf:map>
    </xsl:variable>

    <!-- Step4: Converts lossless XML to JSON output -->
    <xsl:template match="/">
        <xsl:value-of select="xml-to-json($mapped-xml)" />
    </xsl:template>

</xsl:stylesheet>