approvedGitRepositories: []

compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 1w

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistries:
  "https://registry.npmjs.org":
    npmAuthToken: "${NODE_AUTH_TOKEN:-}"

packageExtensions:
  "@patternfly/react-code-editor@*":
    peerDependencies:
      monaco-editor: ">=0.21.0 <1"

yarnPath: .yarn/releases/yarn-4.18.1.cjs
