nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-exec.cjs
    spec: '@yarnpkg/plugin-exec'

yarnPath: .yarn/releases/yarn-3.6.3.cjs

packageExtensions:
  'uniforms-bridge-json-schema@4.0.0-alpha.0':
    dependencies:
      'react': '^18.2.0'

  'storybook-fixtures@*':
    peerDependencies:
      'react-dom': '^18.2.0'

npmRegistryServer: 'http://localhost:4873'
unsafeHttpWhitelist:
  - 'localhost'

npmScopes:
  kaoto-next:
    npmRegistryServer: http://localhost:4873
    npmPublishRegistry: http://localhost:4873
