compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistries:
  "https://registry.npmjs.org":
    npmAuthToken: "${NODE_AUTH_TOKEN:-}"

packageExtensions:
  "@patternfly/react-code-editor@*":
    peerDependencies:
      monaco-editor: ">=0.21.0 <1"
  storybook-fixtures@*:
    peerDependencies:
      react-dom: ^18.2.0
  uniforms-bridge-json-schema@*:
    dependencies:
      react: ^18.2.0

yarnPath: .yarn/releases/yarn-4.4.1.cjs
