nodeLinker: node-modules

npmPublishRegistry: "https://registry.npmjs.org"
npmRegistries:
  "https://registry.npmjs.org":
    npmAuthToken: ${NODE_AUTH_TOKEN:-}

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-exec.cjs
    spec: "@yarnpkg/plugin-exec"

yarnPath: .yarn/releases/yarn-3.6.4.cjs

packageExtensions:
  "uniforms-bridge-json-schema@*":
    dependencies:
      "react": "^18.2.0"

  "storybook-fixtures@*":
    peerDependencies:
      "react-dom": "^18.2.0"
