export const selectors = {
  // export declare const enum selectors {
  CODE_EDITOR: '.pf-v5-c-code-editor',
  CODE_EDITOR_MAIN_INPUT: '.pf-v5-c-code-editor__main > input',
  SPAN_ONLY_CHILD: 'span:only-child',
  MONACO_EDITOR: '.monaco-editor',
  LOADING: 'div:contains("Loading...")',
  REDO_BUTTON: '[data-testid="sourceCode--redoButton"]',
  UNDO_BUTTON: '[data-testid="sourceCode--undoButton"]',
  QUICK_INPUT_MESSAGE: 'input[aria-describedby="quickInput_message"]',
  INMEMORY_URI: '[data-uri^="inmemory://"]',

  //METADATA
  EXPANDABLE_SECTION_TOGGLE: '.pf-v5-c-expandable-section__toggle',
  LIST_ADD_FIELD: '[data-testid="list-add-field"]',

  //NODE CONFIGURATION
  EXPRESSION_EDITOR_CARD: '.expression-metadata-editor-card',
  DF_RESULT_TYPE: '[data-fieldname="resultType"]',
  INPUT_TEXT_INPUT_GROUP: 'input.pf-v5-c-text-input-group__text-input',
  DATA_CONFIG_CARD: '[data-testid="dataformat-config-card"]',
  EXPRESSION_CONFIG_CARD: '[data-testid="expression-config-card"]',
  BUTTON_TOGGLE: 'button.pf-v5-c-menu-toggle__button',
  SPAN_MENU_ITEM_TEXT: 'span.pf-v5-c-menu__item-text',
  SELECT_TYPEAHEAD_CREATE_NEW: '#select-typeahead-kaoto-create-new',
  FILTER_FIELDS: '[data-testid="filter-fields"]',
  FORM_TABS: 'div.form-tabs',
  DIV_TYPEAHEAD: 'div.pf-m-typeahead',
  ADD_STRING_PROPERTY_BUTTON: '[data-testid="properties-add-string-property--btn"]',

  //DESIGN
  FIT_TO_SCREEN: '.fit-to-screen',
  CLOSE_SIDE_BAR: '[data-testid="close-side-bar"]',
  RESIZABLE_SIDE_BAR: '.pf-topology-resizable-side-bar',
  DANGER: '.pf-m-danger',
  CIRCLE_TOPOLOGY_NODE_DECORATOR: 'circle.pf-topology__node__decorator__bg',
  FILTER_BY_NAME_OR_TAG: 'input[placeholder="Filter by name, description or tag"]',
  DELETE_BRANCH_BUTTON: '[data-testid="stepNode__deleteBranch-btn"]',
  CONFIRM_DELETE_BRANCH_BUTTON: '[data-testid="confirmDeleteBranchDialog__btn"]',
  NEW_ENTITY_LIST_DROPDOWN: '[data-testid="new-entity-list-dropdown"]',
  UL_MENU_LIST: 'ul.pf-v5-c-menu__list',
  VISUALIZATION_EMPTY_STATE: '[data-testid="visualization-empty-state"]',
  RUNTIME_SELECTOR_LIST_DROPDOWN: '[data-testid="runtime-selector-list-dropdown"]',
  TITLE_TEXT: '.pf-v5-c-card__title-text',

  //DEFAULT
  LOADING_SCHEMAS: '[data-testid="loading-schemas"]',
  LOADING_CATALOGS: '[data-testid="loading-catalogs"]',
  VISUALIZATION: '#Visualization',
  DESIGN: '[data-testid="Design"]',
  TOPOLOGY_CONTAINER: '.pf-topology-container',
  SOURCE_CODE: '[data-testid="Source Code"]',
  CODE_EDITOR_CODE: '.pf-v5-c-code-editor__code',
  BEANS: '[data-testid="Beans"]',
  METADATA_EDITOR_MODAL_DETAIL: '.metadata-editor-modal-details-view',
  METADATA: '[data-testid="Metadata"]',
  METADATA_EDITOR_FORM: '[data-testid="metadata-editor-form-Metadata"]',
  PIPE_ERRORHANDLER: '[data-testid="Pipe ErrorHandler"]',
  TOPBAR: 'div.pf-v5-c-masthead__content',
  SETTINGS_KEBAB_BUTTON: 'button.pf-v5-c-menu-toggle',
  SETTINGS_LINK: '[data-testid="settings-link"]',
  BUTTON_ABOUT: 'button#about',
  ABOUT_MODAL_BOX: '.pf-v5-c-about-modal-box',
  BUTTON_PLAIN: 'button.pf-v5-c-button.pf-m-plain',
  CATALOG: '[data-testid="Catalog"]',
  COMPONENT_CATALOG_TAB: '[data-testid="component-catalog-tab"]',
  DSL_LIST_DROPDOWN: '[data-testid="dsl-list-dropdown"]',
  DSL_LIST_SELECT: '#dsl-list-select',
  CONFIRMATION_MODAL_CONFIRM: '[data-testid="confirmation-modal-confirm"]',
  NEW_ENTITY_ROUTE: '[data-testid="new-entity-route"]',
  TOGGLE_BUTTON_ROUTE: 'button[data-testid^="toggle-btn-route"]',
  FLOWS_LIST_DROPDOWN: '[data-testid="flows-list-dropdown"]',
  FLOWS_LIST_TABLE: '[data-testid="flows-list-table"]',
  DELETE_BUTTON_ROUTE: 'button[data-testid^="delete-btn-route"]',
} as const;

export type selectorsType = keyof typeof selectors;
