<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:sub="http://www.example.com/SUBSTITUTION" version="3.0" exclude-result-prefixes="sub">
  <xsl:output method="xml" indent="yes"/>
  <xsl:template match="/">
    <sub:Zoo>
      <sub:Dog>
        <sub:name><xsl:value-of select="/sub:Zoo/sub:Dog/sub:name"/></sub:name>
        <sub:breed><xsl:value-of select="/sub:Zoo/sub:Dog/sub:breed"/></sub:breed>
      </sub:Dog>
    </sub:Zoo>
  </xsl:template>
</xsl:stylesheet>
