<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:test="http://www.example.com/test" version="3.0" exclude-result-prefixes="test">
  <xsl:output method="xml" indent="yes"/>
  <xsl:template match="/">
    <test:Root>
      <test:person>
        <test:fax><xsl:value-of select="/test:Root/test:person/test:fax"/></test:fax>
      </test:person>
    </test:Root>
  </xsl:template>
</xsl:stylesheet>
