<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="io.kaoto.datamapper.poc.test" version="3.0" exclude-result-prefixes="ns0">
  <xsl:output method="xml" indent="yes"/>
  <xsl:template match="/">
    <ShipOrder>
      <xsl:attribute name="OrderId"/>
      <OrderPerson><xsl:value-of select="/ns0:ShipOrder/ns0:OrderPerson"/></OrderPerson>
      <Item/>
    </ShipOrder>
  </xsl:template>
</xsl:stylesheet>
