<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="io.kaoto.datamapper.poc.test">
  <xsl:output method="xml" indent="yes"/>
  <xsl:param name="sourceParam1"/>
  <xsl:template match="/">
    <!-- Main ShipOrder mapping -->
    <ShipOrder xmlns="io.kaoto.datamapper.poc.test">
      <!-- Order ID attribute -->
      <xsl:attribute name="OrderId">
        <xsl:value-of select="/ns0:ShipOrder/@OrderId"/>
      </xsl:attribute>
      <!-- Conditional mapping for OrderPerson -->
      <xsl:if test="/ns0:ShipOrder/ns0:OrderPerson != ''">
        <OrderPerson>
          <xsl:value-of select="/ns0:ShipOrder/ns0:OrderPerson"/>
        </OrderPerson>
      </xsl:if>
      <!-- Ship To information -->
      <ShipTo>
        <Name>
          <xsl:value-of select="/ns0:ShipOrder/ns0:ShipTo/ns0:Name"/>
        </Name>
      </ShipTo>
      <!-- Loop through items -->
      <xsl:for-each select="/ns0:ShipOrder/Item">
        <Item>
          <Title>
            <xsl:value-of select="Title"/>
          </Title>
        </Item>
      </xsl:for-each>
    </ShipOrder>
  </xsl:template>
</xsl:stylesheet>
