<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="3.0" xmlns:ns0="io.kaoto.datamapper.poc.test">
    <xsl:output method="xml" indent="yes"/>
    <xsl:template match="/">
        <ShipOrder xmlns="io.kaoto.datamapper.poc.test">
            <xsl:apply-templates select="/ns0:ShipOrder/Item">
                <xsl:sort select="Title" order="ascending"/>
                <xsl:with-param name="prefix" select="'Item:'"/>
            </xsl:apply-templates>
        </ShipOrder>
    </xsl:template>
</xsl:stylesheet>
