<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0">
    <xsl:output method="xml" indent="yes"/>
    <xsl:template match="/">
        <Message837>
            <From>
                <xsl:value-of select="/X12_837P/Header/GS/GS-02"/>
            </From>
            <To>
                <xsl:value-of select="/X12_837P/Header/GS/GS-03"/>
            </To>
            <Date>
                <xsl:value-of select="/X12_837P/Header/GS/GS-04"/>
            </Date>
            <Time>
                <xsl:value-of select="/X12_837P/Header/GS/GS-05"/>
            </Time>
            <xsl:for-each select="/X12_837P/Loop2000/Loop2300">
                <HealthClaim>
                    <SubmitterId>
                        <xsl:value-of select="CLM/CLM-01"/>
                    </SubmitterId>
                    <MonetaryAmount>
                        <xsl:value-of select="CLM/CLM-02"/>
                    </MonetaryAmount>
                    <HealthCareServiceLocationInfo>
                        <FacilityCodeValue>
                            <xsl:value-of select="CLM/CLM-05/C023-01"/>
                        </FacilityCodeValue>
                        <FacilityCodeQualifier>
                            <xsl:value-of select="CLM/CLM-05/C023-02"/>
                        </FacilityCodeQualifier>
                        <ClaimFrequencyTypeCode>
                            <xsl:value-of select="CLM/CLM-05/C023-03"/>
                        </ClaimFrequencyTypeCode>
                    </HealthCareServiceLocationInfo>
                    <YesNoConditionOrResponseCodeFile>
                        <xsl:value-of select="CLM/CLM-06"/>
                    </YesNoConditionOrResponseCodeFile>
                    <ProviderAcceptAssignmentCode>
                        <xsl:value-of select="CLM/CLM-07"/>
                    </ProviderAcceptAssignmentCode>
                    <YesNoConditionOrResponseCodeBenefits>
                        <xsl:value-of select="CLM/CLM-08"/>
                    </YesNoConditionOrResponseCodeBenefits>
                    <ReleaseOfInformationCode>
                        <xsl:value-of select="CLM/CLM-09"/>
                    </ReleaseOfInformationCode>
                </HealthClaim>
            </xsl:for-each>
        </Message837>
    </xsl:template>
</xsl:stylesheet>