import { KaotoOutputChannel } from '../extension/KaotoOutputChannel';

/**
 * Represents a conflict between code-generated and user-defined arguments
 */
export interface ArgumentConflict {
	/** The argument name (e.g., 'management-port', 'console') */
	argument: string;
	/** The value from code defaults */
	codeValue: string;
	/** The value from user settings */
	userValue: string;
	/** Context where the conflict occurred (e.g., 'run', 'export', 'kubernetes') */
	context: string;
}

/**
 * Represents a parsed command-line argument
 */
interface ParsedArgument {
	/** The original argument string */
	original: string;
	/** The argument name without dashes (e.g., 'management-port') */
	name: string;
	/** The argument value if present */
	value?: string;
	/** Whether this is a flag (no value) */
	isFlag: boolean;
}

/**
 * Utility class for detecting and resolving argument conflicts in Camel commands
 */
export class ArgumentConflictDetector {
	/** Cache for parsed arguments to avoid redundant parsing */
	private static readonly parsedCache = new WeakMap<string[], Map<string, ParsedArgument>>();

	/**
	 * Parse a command-line argument into its components
	 * Handles formats: --arg=value, --arg value, --flag
	 *
	 * @param arg - The argument string to parse
	 * @returns Parsed argument information
	 */
	static parseArgument(arg: string): ParsedArgument {
		// Remove quotes if present
		const cleanArg = arg.trim().replaceAll(/^['"]|['"]$/g, '');

		// Handle --arg=value format
		if (cleanArg.includes('=')) {
			const [nameWithDashes, ...valueParts] = cleanArg.split('=');
			const name = nameWithDashes.replace(/^-+/, '');
			const value = valueParts.join('='); // Rejoin in case value contains '='
			return {
				original: arg,
				name: name.toLowerCase(),
				value: value,
				isFlag: false,
			};
		}

		// Handle --flag or --arg (without value)
		const name = cleanArg.replace(/^-+/, '');
		return {
			original: arg,
			name: name.toLowerCase(),
			isFlag: true,
		};
	}

	/**
	 * Get cached parsed arguments for an array, or parse and cache them
	 *
	 * @param args - Array of argument strings
	 * @returns Map of argument strings to parsed arguments
	 */
	private static getCachedParsedArguments(args: string[]): Map<string, ParsedArgument> {
		let cache = this.parsedCache.get(args);
		if (!cache) {
			cache = new Map();
			for (const arg of args) {
				cache.set(arg, this.parseArgument(arg));
			}
			this.parsedCache.set(args, cache);
		}
		return cache;
	}

	/**
	 * Check if an argument with the given name exists in the arguments array
	 *
	 * @param args - Array of argument strings
	 * @param argName - The argument name to search for (without dashes)
	 * @returns True if the argument exists
	 */
	static hasArgument(args: string[], argName: string): boolean {
		const normalizedName = argName.toLowerCase().replace(/^-+/, '');
		const cache = this.getCachedParsedArguments(args);
		for (const parsed of cache.values()) {
			if (parsed.name === normalizedName) {
				return true;
			}
		}
		return false;
	}

	/**
	 * Get the value of an argument from the arguments array
	 *
	 * @param args - Array of argument strings
	 * @param argName - The argument name to search for (without dashes)
	 * @returns The argument value if found, undefined otherwise
	 */
	static getArgumentValue(args: string[], argName: string): string | undefined {
		const normalizedName = argName.toLowerCase().replace(/^-+/, '');
		const cache = this.getCachedParsedArguments(args);

		let i = 0;
		for (const parsed of cache.values()) {
			if (parsed.name === normalizedName) {
				// If value is in the same argument (--arg=value)
				if (parsed.value !== undefined) {
					return parsed.value;
				}

				// If value is in the next argument (--arg value)
				if (i + 1 < args.length && !args[i + 1].startsWith('-')) {
					return args[i + 1];
				}

				// It's a flag
				return undefined;
			}
			i++;
		}

		return undefined;
	}

	/**
	 * Merge code-generated arguments with user-defined arguments, detecting conflicts
	 * User arguments take priority over code arguments
	 *
	 * @param codeArgs - Arguments generated by code
	 * @param userArgs - Arguments from user settings
	 * @param context - Context identifier for conflict reporting
	 * @returns Object containing merged arguments and detected conflicts
	 */
	static mergeArguments(codeArgs: string[], userArgs: string[], context: string): { merged: string[]; conflicts: ArgumentConflict[] } {
		const conflicts: ArgumentConflict[] = [];
		const mergedArgs: string[] = [...userArgs]; // Start with user args (they have priority)

		// Create a Set of normalized user argument names for O(1) lookup
		const userArgNames = new Set(userArgs.map((arg) => this.parseArgument(arg).name));

		// Check each code argument
		for (const codeArg of codeArgs) {
			const parsedCodeArg = this.parseArgument(codeArg);

			// Check if user has defined this argument
			if (userArgNames.has(parsedCodeArg.name)) {
				const userValue = this.getArgumentValue(userArgs, parsedCodeArg.name);
				const codeValue = parsedCodeArg.value ?? '(flag)';

				// Record the conflict
				conflicts.push({
					argument: parsedCodeArg.name,
					codeValue: codeValue,
					userValue: userValue ?? '(flag)',
					context: context,
				});

				// Don't add the code argument (user argument already in merged array)
			} else {
				// No conflict, add the code argument
				mergedArgs.push(codeArg);
			}
		}

		return { merged: mergedArgs, conflicts };
	}

	/**
	 * Check if any of the specified argument names exist in the user arguments
	 * Useful for checking multiple related arguments (e.g., --port and --management-port)
	 *
	 * @param userArgs - Array of user-defined argument strings
	 * @param argNames - Array of argument names to check for
	 * @returns True if any of the arguments exist
	 */
	static hasAnyArgument(userArgs: string[], argNames: string[]): boolean {
		return argNames.some((argName) => this.hasArgument(userArgs, argName));
	}

	/**
	 * Remove arguments with specified names from an array
	 *
	 * @param args - Array of argument strings
	 * @param argNames - Array of argument names to remove
	 * @returns New array with specified arguments removed
	 */
	static removeArguments(args: string[], argNames: string[]): string[] {
		const normalizedNames = new Set(argNames.map((name) => name.toLowerCase().replace(/^-+/, '')));

		return args.filter((arg) => {
			const parsed = this.parseArgument(arg);
			return !normalizedNames.has(parsed.name);
		});
	}

	/**
	 * Extract port number from arguments array
	 * Checks for --management-port and --port arguments
	 *
	 * @param args - Array of argument strings
	 * @returns Port number if found, undefined otherwise
	 */
	static extractPortValue(args: string[]): number | undefined {
		// Check for --management-port first (takes priority in Camel 4.14+)
		const managementPort = this.getArgumentValue(args, 'management-port');
		if (managementPort !== undefined) {
			const port = Number.parseInt(managementPort, 10);
			if (Number.isNaN(port)) {
				KaotoOutputChannel.logWarning(`Invalid port value for --management-port: "${managementPort}". Expected a valid number.`);
				return undefined;
			}
			return port;
		}

		// Check for --port
		const portValue = this.getArgumentValue(args, 'port');
		if (portValue !== undefined) {
			const port = Number.parseInt(portValue, 10);
			if (Number.isNaN(port)) {
				KaotoOutputChannel.logWarning(`Invalid port value for --port: "${portValue}". Expected a valid number.`);
				return undefined;
			}
			return port;
		}

		return undefined;
	}
}
