<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="3.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:po="http://www.kaoto.io/purchaseorder" xmlns:ai="http://www.kaoto.io/account" xmlns:li="http://www.kaoto.io/logistics" xmlns:si="http://www.kaoto.io/stock" xmlns:bi="http://www.kaoto.io/billing" xmlns:party="http://www.kaoto.io/common/party" xmlns:addr="http://www.kaoto.io/common/address" xmlns:fin="http://www.kaoto.io/common/financial" xmlns:dt="http://www.kaoto.io/common/datetime" xmlns:ns0="http://www.kaoto.io/shiporder" exclude-result-prefixes="xs po ai li si bi party addr fin dt ns0">
    <xsl:output method="xml" indent="yes"/>
    <xsl:param name="billingInfoDoc"/>
    <xsl:param name="accountInfoDoc"/>
    <xsl:param name="logisticsInfoDoc"/>
    <xsl:param name="stockInfoDoc"/>
    <xsl:template match="/">
        <ShipOrder xmlns="http://www.kaoto.io/shiporder">
            <xsl:variable name="isExpress" select="$logisticsInfoDoc//li:LogisticsInfo/li:ShippingPreferences/li:ExpressShipping = 'true'"/>
            <xsl:variable name="isInternational" select="po:PurchaseOrder/po:ShippingDetails/addr:StandardAddress/addr:Country != 'USA'"/>
            <xsl:variable name="accountHolder" select="$accountInfoDoc//ai:AccountInfo[ai:AccountHeader/ai:AccountID = /po:PurchaseOrder/po:Buyer/party:PartyID]/ai:AccountHolder"/>
            <xsl:variable name="accountContactInfo" select="$accountInfoDoc//ai:AccountInfo[ai:AccountHeader/ai:AccountID = /po:PurchaseOrder/po:Buyer/party:PartyID]/ai:ContactInformation"/>
            <xsl:variable name="itemWeights">
                <xsl:for-each select="po:PurchaseOrder/po:OrderItems/po:OrderItem">
                    <xsl:variable name="sku" select="po:ProductID"/>
                    <xsl:variable name="stockWeight" select="$stockInfoDoc//si:StockInfo/si:InventoryItems/si:StandardItem[si:SKU = $sku]/si:Weight"/>
                    <w>
                        <xsl:value-of select="(if ($stockWeight) then xs:decimal($stockWeight) else 1.0) * xs:decimal(po:Quantity)"/>
                    </w>
                </xsl:for-each>
            </xsl:variable>
            <xsl:variable name="totalWeight" select="sum($itemWeights/w)"/>
            <xsl:variable name="lineItemValues">
                <xsl:for-each select="po:PurchaseOrder/po:OrderItems/po:OrderItem">
                    <w>
                        <xsl:value-of select="xs:decimal(po:UnitPrice) * xs:decimal(po:Quantity)"/>
                    </w>
                </xsl:for-each>
            </xsl:variable>
            <xsl:variable name="totalValue" select="sum($lineItemValues/w)"/>
            <xsl:variable name="daysToAdd">
                <xsl:choose>
                    <xsl:when test="$isExpress">
                        <xsl:value-of select="3"/>
                    </xsl:when>
                    <xsl:otherwise>
                        <xsl:value-of select="5"/>
                    </xsl:otherwise>
                </xsl:choose>
            </xsl:variable>
            <xsl:attribute name="orderVersion">
                <xsl:value-of select="'1.0.0'"/>
            </xsl:attribute>
            <xsl:attribute name="schemaVersion">
                <xsl:value-of select="1.0"/>
            </xsl:attribute>
            <xsl:attribute name="totalWeight">
                <xsl:value-of select="if ($totalWeight &gt; 0) then $totalWeight else '5.0'"/>
            </xsl:attribute>
            <xsl:attribute name="totalPackages">
                <xsl:value-of select="1"/>
            </xsl:attribute>
            <xsl:attribute name="signatureRequired">
                <xsl:value-of select="if (po:PurchaseOrder/po:ShippingDetails/po:SignatureRequired = 'true') then 'true' else 'false'"/>
            </xsl:attribute>
            <xsl:attribute name="allowPartialShipment">
                <xsl:value-of select="'true'"/>
            </xsl:attribute>
            <xsl:attribute name="priorityProcessing">
                <xsl:value-of select="if ($logisticsInfoDoc//li:LogisticsInfo/li:LogisticsHeader/li:ShipmentPriority = ('Critical', 'Urgent')) then 'true' else 'false'"/>
            </xsl:attribute>
            <!-- Cross-system order references linking all 5 source documents -->
            <OrderIdentification>
                <ShipOrderID>
                    <xsl:value-of select="concat('SO-', format-dateTime(current-dateTime(), '[Y0001][M01][D01]-[H01][m01]'), '-', substring(po:PurchaseOrder/po:OrderHeader/po:OrderID, 1, 8))"/>
                </ShipOrderID>
                <PurchaseOrderReference>
                    <xsl:attribute name="referenceType">
                        <xsl:value-of select="'PurchaseOrder'"/>
                    </xsl:attribute>
                    <ReferenceID>
                        <xsl:value-of select="po:PurchaseOrder/po:OrderHeader/po:OrderID"/>
                    </ReferenceID>
                    <ReferenceNumber>
                        <xsl:value-of select="po:PurchaseOrder/po:OrderHeader/po:OrderNumber"/>
                    </ReferenceNumber>
                    <ReferenceDate>
                        <xsl:value-of select="format-dateTime(po:PurchaseOrder/po:OrderHeader/po:OrderDate, '[Y0001]-[M01]-[D01]')"/>
                    </ReferenceDate>
                </PurchaseOrderReference>
                <xsl:if test="po:PurchaseOrder/po:OrderHeader/po:CustomerReference">
                    <CustomerOrderNumber>
                        <xsl:value-of select="po:PurchaseOrder/po:OrderHeader/po:CustomerReference"/>
                    </CustomerOrderNumber>
                </xsl:if>
                <ExternalReferences>
                    <ExternalReference>
                        <SystemName>
                            <xsl:value-of select="'BillingSystem'"/>
                        </SystemName>
                        <ReferenceID>
                            <xsl:value-of select="$billingInfoDoc//bi:BillingInfo/bi:BillingHeader/bi:BillingID"/>
                        </ReferenceID>
                        <ReferenceType>
                            <xsl:value-of select="'BillingID'"/>
                        </ReferenceType>
                    </ExternalReference>
                    <ExternalReference>
                        <SystemName>
                            <xsl:value-of select="'AccountSystem'"/>
                        </SystemName>
                        <ReferenceID>
                            <xsl:value-of select="$accountInfoDoc//ai:AccountInfo[ai:AccountHeader/ai:AccountID = /po:PurchaseOrder/po:Buyer/party:PartyID]/ai:AccountHeader/ai:AccountID"/>
                        </ReferenceID>
                        <ReferenceType>
                            <xsl:value-of select="'AccountID'"/>
                        </ReferenceType>
                    </ExternalReference>
                    <ExternalReference>
                        <SystemName>
                            <xsl:value-of select="'LogisticsSystem'"/>
                        </SystemName>
                        <ReferenceID>
                            <xsl:value-of select="$logisticsInfoDoc//li:LogisticsInfo/li:LogisticsHeader/li:LogisticsID"/>
                        </ReferenceID>
                        <ReferenceType>
                            <xsl:value-of select="'LogisticsID'"/>
                        </ReferenceType>
                    </ExternalReference>
                    <ExternalReference>
                        <SystemName>
                            <xsl:value-of select="'InventorySystem'"/>
                        </SystemName>
                        <ReferenceID>
                            <xsl:value-of select="$stockInfoDoc//si:StockInfo/si:StockHeader/si:StockID"/>
                        </ReferenceID>
                        <ReferenceType>
                            <xsl:value-of select="'InventoryID'"/>
                        </ReferenceType>
                    </ExternalReference>
                </ExternalReferences>
            </OrderIdentification>
            <!-- Timestamps and processing metadata -->
            <OrderMetadata>
                <CreatedDateTime>
                    <xsl:value-of select="current-dateTime()"/>
                </CreatedDateTime>
                <LastModifiedDateTime>
                    <xsl:value-of select="current-dateTime()"/>
                </LastModifiedDateTime>
                <CreatedBy>
                    <UserID>
                        <xsl:value-of select="'XSLT-DM-001'"/>
                    </UserID>
                    <UserName>
                        <xsl:value-of select="'DataMapper XSLT Transformation'"/>
                    </UserName>
                    <UserType>
                        <xsl:value-of select="'System'"/>
                    </UserType>
                </CreatedBy>
                <ProcessingStatus>
                    <xsl:value-of select="'Submitted'"/>
                </ProcessingStatus>
                <SourceSystem>
                    <xsl:value-of select="'XSLT-DataMapper-Transform'"/>
                </SourceSystem>
            </OrderMetadata>
            <!-- Customer from AccountInfo joined by Buyer PartyID -->
            <CustomerInformation>
                <CustomerID>
                    <xsl:value-of select="po:PurchaseOrder/po:Buyer/party:PartyID"/>
                </CustomerID>
                <CustomerDetails>
                    <!-- PATTERN: xsl:copy-of copies same-namespace subtree into party:Person container -->
                    <xsl:choose>
                        <xsl:when test="$accountHolder/party:PersonName">
                            <xsl:copy-of select="$accountHolder/*"/>
                        </xsl:when>
                        <xsl:otherwise>
                            <Person xmlns="http://www.kaoto.io/common/party"/>
                        </xsl:otherwise>
                    </xsl:choose>
                </CustomerDetails>
                <ContactInformation>
                    <PrimaryPhone>
                        <xsl:value-of select="if ($accountContactInfo/ai:PrimaryPhone) then $accountContactInfo/ai:PrimaryPhone else '000-000-0000'"/>
                    </PrimaryPhone>
                    <xsl:if test="$accountContactInfo/ai:MobilePhone">
                        <AlternatePhone>
                            <xsl:value-of select="$accountContactInfo/ai:MobilePhone"/>
                        </AlternatePhone>
                    </xsl:if>
                    <EmailAddress>
                        <xsl:value-of select="if ($accountContactInfo/ai:PrimaryEmail) then $accountContactInfo/ai:PrimaryEmail else 'unknown@example.com'"/>
                    </EmailAddress>
                    <PreferredContactMethod>
                        <xsl:value-of select="if ($accountContactInfo/ai:PreferredContactMethod) then $accountContactInfo/ai:PreferredContactMethod else 'Email'"/>
                    </PreferredContactMethod>
                </ContactInformation>
                <xsl:if test="$logisticsInfoDoc//li:LogisticsInfo/li:ShippingPreferences">
                    <CustomerPreferences>
                        <xsl:if test="$logisticsInfoDoc//li:LogisticsInfo/li:ShippingPreferences/li:PreferredCarrier">
                            <PreferredCarrier>
                                <xsl:value-of select="$logisticsInfoDoc//li:LogisticsInfo/li:ShippingPreferences/li:PreferredCarrier"/>
                            </PreferredCarrier>
                        </xsl:if>
                        <xsl:if test="$logisticsInfoDoc//li:LogisticsInfo/li:ShippingPreferences/li:DeliveryInstructions">
                            <DeliveryInstructions>
                                <xsl:value-of select="$logisticsInfoDoc//li:LogisticsInfo/li:ShippingPreferences/li:DeliveryInstructions"/>
                            </DeliveryInstructions>
                        </xsl:if>
                        <LeaveAtDoor>
                            <xsl:value-of select="if ($logisticsInfoDoc//li:LogisticsInfo/li:ShippingPreferences/li:LeaveAtDoor) then $logisticsInfoDoc//li:LogisticsInfo/li:ShippingPreferences/li:LeaveAtDoor else 'false'"/>
                        </LeaveAtDoor>
                        <NotificationPreferences>
                            <EmailNotifications>
                                <xsl:value-of select="'true'"/>
                            </EmailNotifications>
                            <SMSNotifications>
                                <xsl:value-of select="if ($logisticsInfoDoc//li:LogisticsInfo/li:ShippingPreferences/li:SMSNotifications) then $logisticsInfoDoc//li:LogisticsInfo/li:ShippingPreferences/li:SMSNotifications else 'false'"/>
                            </SMSNotifications>
                            <NotifyOnShipment>
                                <xsl:value-of select="'true'"/>
                            </NotifyOnShipment>
                            <NotifyOnDelivery>
                                <xsl:value-of select="'true'"/>
                            </NotifyOnDelivery>
                            <NotifyOnException>
                                <xsl:value-of select="'true'"/>
                            </NotifyOnException>
                        </NotificationPreferences>
                    </CustomerPreferences>
                </xsl:if>
            </CustomerInformation>
            <!-- Line items with StockInfo product weight lookup -->
            <ShipmentDetails>
                <!-- PATTERN: xsl:for-each iterating source OrderItems with xsl:sort -->
                <ShipmentLineItems>
                    <xsl:for-each select="po:PurchaseOrder/po:OrderItems/po:OrderItem">
                        <xsl:sort select="po:ProductName"/>
                        <LineItem>
                            <xsl:attribute name="lineNumber">
                                <xsl:value-of select="position()"/>
                            </xsl:attribute>
                            <LineItemID>
                                <xsl:value-of select="concat('LI-', format-number(position(), '0000'))"/>
                            </LineItemID>
                            <ProductInformation>
                                <SKU>
                                    <xsl:value-of select="po:ProductID"/>
                                </SKU>
                                <ProductName>
                                    <xsl:value-of select="po:ProductName"/>
                                </ProductName>
                                <xsl:if test="po:ProductCategory">
                                    <ProductDescription>
                                        <xsl:value-of select="concat(if (po:Manufacturer) then concat(po:Manufacturer, ' ') else '', po:ProductName, ' - ', po:ProductCategory)"/>
                                    </ProductDescription>
                                </xsl:if>
                                <xsl:if test="po:UPC">
                                    <UPC>
                                        <xsl:value-of select="po:UPC"/>
                                    </UPC>
                                </xsl:if>
                                <Weight>
                                    <xsl:variable name="itemStockInfo" select="$stockInfoDoc//si:StockInfo/si:InventoryItems/si:StandardItem[si:SKU = current()/po:ProductID]"/>
                                    <xsl:value-of select="if ($itemStockInfo/si:Weight) then $itemStockInfo/si:Weight else '1.0'"/>
                                </Weight>
                                <xsl:if test="po:ProductSpecifications/po:PhysicalProduct/po:Dimensions">
                                    <Dimensions>
                                        <xsl:attribute name="unit">
                                            <xsl:value-of select="'Inches'"/>
                                        </xsl:attribute>
                                        <Length>
                                            <xsl:value-of select="po:ProductSpecifications/po:PhysicalProduct/po:Dimensions/po:Length"/>
                                        </Length>
                                        <Width>
                                            <xsl:value-of select="po:ProductSpecifications/po:PhysicalProduct/po:Dimensions/po:Width"/>
                                        </Width>
                                        <Height>
                                            <xsl:value-of select="po:ProductSpecifications/po:PhysicalProduct/po:Dimensions/po:Height"/>
                                        </Height>
                                    </Dimensions>
                                </xsl:if>
                            </ProductInformation>
                            <Quantity>
                                <xsl:value-of select="po:Quantity"/>
                            </Quantity>
                            <UnitPrice>
                                <xsl:value-of select="po:UnitPrice"/>
                            </UnitPrice>
                            <LineTotal>
                                <xsl:value-of select="format-number(xs:decimal(po:UnitPrice) * xs:decimal(po:Quantity), '0.00')"/>
                            </LineTotal>
                            <!-- PATTERN: xsl:if inside xsl:for-each -->
                            <xsl:if test="$stockInfoDoc//si:StockInfo/si:WarehouseLocations/si:Warehouse[1]/si:WarehouseName">
                                <InventoryLocation>
                                    <xsl:value-of select="$stockInfoDoc//si:StockInfo/si:WarehouseLocations/si:Warehouse[1]/si:WarehouseName"/>
                                </InventoryLocation>
                            </xsl:if>
                        </LineItem>
                    </xsl:for-each>
                </ShipmentLineItems>
                <TotalQuantity>
                    <xsl:value-of select="sum(po:PurchaseOrder/po:OrderItems/po:OrderItem/po:Quantity)"/>
                </TotalQuantity>
                <TotalValue>
                    <xsl:value-of select="format-number($totalValue, '0.00')"/>
                </TotalValue>
            </ShipmentDetails>
            <!-- Package dimensions and container selection by total weight -->
            <PackagingInformation>
                <Packages>
                    <Package>
                        <xsl:attribute name="packageNumber">
                            <xsl:value-of select="1"/>
                        </xsl:attribute>
                        <PackageID>
                            <xsl:value-of select="concat('PKG-', format-dateTime(current-dateTime(), '[Y0001][M01][D01]'), '-001')"/>
                        </PackageID>
                        <PackageType>
                            <xsl:choose>
                                <xsl:when test="$totalWeight &lt;= 2">
                                    <xsl:value-of select="'Envelope'"/>
                                </xsl:when>
                                <xsl:when test="$totalWeight &gt; 50">
                                    <xsl:value-of select="'Pallet'"/>
                                </xsl:when>
                                <xsl:otherwise>
                                    <xsl:value-of select="'Box'"/>
                                </xsl:otherwise>
                            </xsl:choose>
                        </PackageType>
                        <Dimensions>
                            <xsl:attribute name="unit">
                                <xsl:value-of select="'Inches'"/>
                            </xsl:attribute>
                            <Length>
                                <xsl:value-of select="12"/>
                            </Length>
                            <Width>
                                <xsl:value-of select="10"/>
                            </Width>
                            <Height>
                                <xsl:value-of select="8"/>
                            </Height>
                        </Dimensions>
                        <Weight>
                            <xsl:value-of select="if ($totalWeight &gt; 0) then $totalWeight else '5.0'"/>
                        </Weight>
                        <PackageContents>
                            <xsl:for-each select="po:PurchaseOrder/po:OrderItems/po:OrderItem">
                                <xsl:sort select="po:ProductName"/>
                                <ContentItem>
                                    <LineItemReference>
                                        <xsl:value-of select="concat('LI-', format-number(position(), '0000'))"/>
                                    </LineItemReference>
                                    <Quantity>
                                        <xsl:value-of select="po:Quantity"/>
                                    </Quantity>
                                </ContentItem>
                            </xsl:for-each>
                        </PackageContents>
                    </Package>
                </Packages>
                <!-- PATTERN: Abstract element in sequence - Concrete substitution group elements -->
                <xsl:choose>
                    <xsl:when test="$totalWeight &lt;= 2">
                        <PaddedEnvelope>
                            <ContainerID>
                                <xsl:value-of select="concat('ENV-', format-dateTime(current-dateTime(), '[Y0001][M01][D01]'), '-001')"/>
                            </ContainerID>
                            <ContainerDescription>
                                <xsl:value-of select="'Padded envelope for lightweight items'"/>
                            </ContainerDescription>
                            <Dimensions>
                                <xsl:attribute name="unit">
                                    <xsl:value-of select="'Inches'"/>
                                </xsl:attribute>
                                <Length>
                                    <xsl:value-of select="12"/>
                                </Length>
                                <Width>
                                    <xsl:value-of select="9"/>
                                </Width>
                                <Height>
                                    <xsl:value-of select="1"/>
                                </Height>
                            </Dimensions>
                            <MaxWeight>
                                <xsl:value-of select="2"/>
                            </MaxWeight>
                            <PaddingType>
                                <xsl:value-of select="'BubbleWrap'"/>
                            </PaddingType>
                        </PaddedEnvelope>
                    </xsl:when>
                    <xsl:when test="$totalWeight &gt; 50">
                        <Pallet>
                            <ContainerID>
                                <xsl:value-of select="concat('PLT-', format-dateTime(current-dateTime(), '[Y0001][M01][D01]'), '-001')"/>
                            </ContainerID>
                            <ContainerDescription>
                                <xsl:value-of select="'Standard pallet for heavy shipments'"/>
                            </ContainerDescription>
                            <Dimensions>
                                <xsl:attribute name="unit">
                                    <xsl:value-of select="'Inches'"/>
                                </xsl:attribute>
                                <Length>
                                    <xsl:value-of select="48"/>
                                </Length>
                                <Width>
                                    <xsl:value-of select="40"/>
                                </Width>
                                <Height>
                                    <xsl:value-of select="6"/>
                                </Height>
                            </Dimensions>
                            <MaxWeight>
                                <xsl:value-of select="2000"/>
                            </MaxWeight>
                            <PalletSize>
                                <xsl:value-of select="'Standard48x40'"/>
                            </PalletSize>
                        </Pallet>
                    </xsl:when>
                    <xsl:otherwise>
                        <StandardBox>
                            <ContainerID>
                                <xsl:value-of select="concat('BOX-', format-dateTime(current-dateTime(), '[Y0001][M01][D01]'), '-001')"/>
                            </ContainerID>
                            <ContainerDescription>
                                <xsl:value-of select="'Standard shipping box'"/>
                            </ContainerDescription>
                            <Dimensions>
                                <xsl:attribute name="unit">
                                    <xsl:value-of select="'Inches'"/>
                                </xsl:attribute>
                                <Length>
                                    <xsl:value-of select="12"/>
                                </Length>
                                <Width>
                                    <xsl:value-of select="10"/>
                                </Width>
                                <Height>
                                    <xsl:value-of select="8"/>
                                </Height>
                            </Dimensions>
                            <MaxWeight>
                                <xsl:value-of select="50"/>
                            </MaxWeight>
                            <BoxStrength>
                                <xsl:value-of select="if ($totalWeight &gt; 20) then 'DoubleWall' else 'SingleWall'"/>
                            </BoxStrength>
                        </StandardBox>
                    </xsl:otherwise>
                </xsl:choose>
                <PackagingMaterials>
                    <xsl:value-of select="if ($totalWeight &gt; 50) then 'Heavy-duty shrink wrap and corner protectors' else if ($totalWeight &gt; 20) then 'Bubble wrap and packing peanuts' else 'Tissue paper and air pillows'"/>
                </PackagingMaterials>
                <SpecialPackaging>
                    <xsl:value-of select="boolean($stockInfoDoc//si:StockInfo/si:InventoryItems/si:PerishableItem or $stockInfoDoc//si:StockInfo/si:InventoryItems/si:HazardousItem)"/>
                </SpecialPackaging>
            </PackagingInformation>
            <!-- PATTERN: xsl:copy-of copies entire addr:StandardAddress container element -->
            <DeliveryAddress>
                <xsl:choose>
                    <xsl:when test="po:PurchaseOrder/po:ShippingDetails/addr:StandardAddress">
                        <xsl:copy-of select="po:PurchaseOrder/po:ShippingDetails/addr:StandardAddress"/>
                    </xsl:when>
                    <xsl:when test="po:PurchaseOrder/po:ShippingDetails/addr:InternationalAddress">
                        <xsl:copy-of select="po:PurchaseOrder/po:ShippingDetails/addr:InternationalAddress"/>
                    </xsl:when>
                    <xsl:when test="po:PurchaseOrder/po:ShippingDetails/addr:POBoxAddress">
                        <xsl:copy-of select="po:PurchaseOrder/po:ShippingDetails/addr:POBoxAddress"/>
                    </xsl:when>
                    <xsl:when test="po:PurchaseOrder/po:ShippingDetails/addr:MilitaryAddress">
                        <xsl:copy-of select="po:PurchaseOrder/po:ShippingDetails/addr:MilitaryAddress"/>
                    </xsl:when>
                    <xsl:otherwise>
                        <StandardAddress xmlns="http://www.kaoto.io/common/address">
                            <AddressID>
                                <xsl:value-of select="'DEFAULT'"/>
                            </AddressID>
                            <AddressLine1>
                                <xsl:value-of select="'123 Main Street'"/>
                            </AddressLine1>
                            <City>
                                <xsl:value-of select="'Anytown'"/>
                            </City>
                            <Country>
                                <xsl:value-of select="'USA'"/>
                            </Country>
                            <StateProvince>
                                <xsl:value-of select="'CA'"/>
                            </StateProvince>
                            <PostalCode>
                                <xsl:value-of select="12345"/>
                            </PostalCode>
                        </StandardAddress>
                    </xsl:otherwise>
                </xsl:choose>
            </DeliveryAddress>
            <!-- Unconditional copy-of from BillingInfo bill-to address -->
            <BillingAddress>
                <xsl:choose>
                    <xsl:when test="$billingInfoDoc//bi:BillingInfo/addr:StandardAddress">
                        <xsl:copy-of select="$billingInfoDoc//bi:BillingInfo/addr:StandardAddress"/>
                    </xsl:when>
                    <xsl:when test="$billingInfoDoc//bi:BillingInfo/addr:InternationalAddress">
                        <xsl:copy-of select="$billingInfoDoc//bi:BillingInfo/addr:InternationalAddress"/>
                    </xsl:when>
                    <xsl:when test="$billingInfoDoc//bi:BillingInfo/addr:POBoxAddress">
                        <xsl:copy-of select="$billingInfoDoc//bi:BillingInfo/addr:POBoxAddress"/>
                    </xsl:when>
                    <xsl:when test="$billingInfoDoc//bi:BillingInfo/addr:MilitaryAddress">
                        <xsl:copy-of select="$billingInfoDoc//bi:BillingInfo/addr:MilitaryAddress"/>
                    </xsl:when>
                    <xsl:otherwise>
                        <StandardAddress xmlns="http://www.kaoto.io/common/address"/>
                    </xsl:otherwise>
                </xsl:choose>
            </BillingAddress>
            <!-- Static copy-of from StockInfo first warehouse address -->
            <ReturnAddress>
                <xsl:copy-of select="$stockInfoDoc//si:StockInfo/si:WarehouseLocations/si:Warehouse[1]/addr:StandardAddress"/>
            </ReturnAddress>
            <!-- Carrier from LogisticsInfo shipping preferences -->
            <CarrierSelection>
                <xsl:attribute name="selectionMethod">
                    <xsl:value-of select="if ($isExpress) then 'TimeOptimized' else 'CostOptimized'"/>
                </xsl:attribute>
                <!-- PATTERN: Abstract element in sequence (maxOccurs=1) - Concrete substitution group element -->
                <xsl:choose>
                    <xsl:when test="$isExpress">
                        <ExpressDelivery>
                            <MethodCode>
                                <xsl:value-of select="'EXP'"/>
                            </MethodCode>
                            <MethodDescription>
                                <xsl:value-of select="'Express delivery within 3 business days'"/>
                            </MethodDescription>
                            <EstimatedDeliveryDays>
                                <xsl:value-of select="3"/>
                            </EstimatedDeliveryDays>
                            <GuaranteedDeliveryTime>
                                <xsl:value-of select="'17:00:00'"/>
                            </GuaranteedDeliveryTime>
                            <PremiumCharge>
                                <xsl:value-of select="'8.00'"/>
                            </PremiumCharge>
                        </ExpressDelivery>
                    </xsl:when>
                    <xsl:when test="$logisticsInfoDoc//li:LogisticsInfo/li:ShippingPreferences/li:ScheduledDelivery">
                        <ScheduledDelivery>
                            <MethodCode>
                                <xsl:value-of select="'SCHED'"/>
                            </MethodCode>
                            <MethodDescription>
                                <xsl:value-of select="'Scheduled delivery at specified date and time'"/>
                            </MethodDescription>
                            <EstimatedDeliveryDays>
                                <xsl:value-of select="$daysToAdd"/>
                            </EstimatedDeliveryDays>
                            <ScheduledDate>
                                <xsl:value-of select="$logisticsInfoDoc//li:LogisticsInfo/li:ShippingPreferences/li:ScheduledDelivery/li:Date"/>
                            </ScheduledDate>
                            <ScheduledTimeWindow>
                                <StartTime>
                                    <xsl:value-of select="'09:00:00'"/>
                                </StartTime>
                                <EndTime>
                                    <xsl:value-of select="'17:00:00'"/>
                                </EndTime>
                            </ScheduledTimeWindow>
                        </ScheduledDelivery>
                    </xsl:when>
                    <xsl:otherwise>
                        <StandardDelivery>
                            <MethodCode>
                                <xsl:value-of select="'STD'"/>
                            </MethodCode>
                            <MethodDescription>
                                <xsl:value-of select="'Standard ground delivery'"/>
                            </MethodDescription>
                            <EstimatedDeliveryDays>
                                <xsl:value-of select="5"/>
                            </EstimatedDeliveryDays>
                        </StandardDelivery>
                    </xsl:otherwise>
                </xsl:choose>
                <CarrierName>
                    <xsl:value-of select="if ($logisticsInfoDoc//li:LogisticsInfo/li:ShippingPreferences/li:PreferredCarrier) then $logisticsInfoDoc//li:LogisticsInfo/li:ShippingPreferences/li:PreferredCarrier else 'UPS'"/>
                </CarrierName>
                <CarrierCode>
                    <xsl:choose>
                        <xsl:when test="$logisticsInfoDoc//li:LogisticsInfo/li:ShippingPreferences/li:PreferredCarrier = 'FedEx'">
                            <xsl:value-of select="'FDXG'"/>
                        </xsl:when>
                        <xsl:when test="$logisticsInfoDoc//li:LogisticsInfo/li:ShippingPreferences/li:PreferredCarrier = 'USPS'">
                            <xsl:value-of select="'USPS'"/>
                        </xsl:when>
                        <xsl:otherwise>
                            <xsl:value-of select="'UPSN'"/>
                        </xsl:otherwise>
                    </xsl:choose>
                </CarrierCode>
                <ServiceName>
                    <xsl:value-of select="if ($isExpress) then 'Express' else 'Ground'"/>
                </ServiceName>
                <ServiceCode>
                    <xsl:value-of select="if ($isExpress) then '13' else '03'"/>
                </ServiceCode>
                <EstimatedDeliveryDate>
                    <xsl:value-of select="format-date(current-date() + xs:dayTimeDuration(concat('P', $daysToAdd, 'D')), '[Y0001]-[M01]-[D01]')"/>
                </EstimatedDeliveryDate>
                <xsl:if test="$logisticsInfoDoc//li:LogisticsInfo/li:CarrierInformation/li:CarrierAccountNumber">
                    <CarrierAccountNumber>
                        <xsl:value-of select="$logisticsInfoDoc//li:LogisticsInfo/li:CarrierInformation/li:CarrierAccountNumber"/>
                    </CarrierAccountNumber>
                </xsl:if>
            </CarrierSelection>
            <!-- Delivery preferences from LogisticsInfo -->
            <DeliveryPreferences>
                <xsl:if test="po:PurchaseOrder/po:OrderHeader/po:RequestedDeliveryDate">
                    <RequestedDeliveryDate>
                        <xsl:value-of select="po:PurchaseOrder/po:OrderHeader/po:RequestedDeliveryDate"/>
                    </RequestedDeliveryDate>
                </xsl:if>
                <xsl:if test="$logisticsInfoDoc//li:LogisticsInfo/li:ShippingPreferences/li:ScheduledDelivery/li:TimeWindow">
                    <DeliveryTimeWindow>
                        <StartTime>
                            <xsl:value-of select="$logisticsInfoDoc//li:LogisticsInfo/li:ShippingPreferences/li:ScheduledDelivery/li:TimeWindow/dt:StartTime"/>
                        </StartTime>
                        <EndTime>
                            <xsl:value-of select="$logisticsInfoDoc//li:LogisticsInfo/li:ShippingPreferences/li:ScheduledDelivery/li:TimeWindow/dt:EndTime"/>
                        </EndTime>
                    </DeliveryTimeWindow>
                </xsl:if>
                <xsl:if test="$logisticsInfoDoc//li:LogisticsInfo/li:ShippingPreferences/li:DeliveryInstructions">
                    <DeliveryInstructions>
                        <xsl:value-of select="$logisticsInfoDoc//li:LogisticsInfo/li:ShippingPreferences/li:DeliveryInstructions"/>
                    </DeliveryInstructions>
                </xsl:if>
                <AuthorityToLeave>
                    <xsl:value-of select="if ($logisticsInfoDoc//li:LogisticsInfo/li:ShippingPreferences/li:LeaveAtDoor) then $logisticsInfoDoc//li:LogisticsInfo/li:ShippingPreferences/li:LeaveAtDoor else 'false'"/>
                </AuthorityToLeave>
            </DeliveryPreferences>
            <!-- Hazmat and perishable handling from StockInfo -->
            <xsl:if test="$stockInfoDoc//si:StockInfo/si:InventoryItems/si:HazardousItem or $stockInfoDoc//si:StockInfo/si:InventoryItems/si:PerishableItem or po:PurchaseOrder/po:ShippingDetails/po:InsuranceRequired = 'true'">
                <SpecialHandling>
                    <HandlingCodes>
                        <xsl:if test="$stockInfoDoc//si:StockInfo/si:InventoryItems/si:HazardousItem">
                            <HandlingCode>
                                <xsl:value-of select="'Hazmat'"/>
                            </HandlingCode>
                        </xsl:if>
                        <xsl:if test="$stockInfoDoc//si:StockInfo/si:InventoryItems/si:PerishableItem">
                            <HandlingCode>
                                <xsl:value-of select="'Perishable'"/>
                            </HandlingCode>
                            <HandlingCode>
                                <xsl:value-of select="'TemperatureControlled'"/>
                            </HandlingCode>
                        </xsl:if>
                        <xsl:if test="po:PurchaseOrder/po:ShippingDetails/po:InsuranceRequired = 'true'">
                            <HandlingCode>
                                <xsl:value-of select="'HighValue'"/>
                            </HandlingCode>
                        </xsl:if>
                        <xsl:if test="$totalWeight &gt; 50">
                            <HandlingCode>
                                <xsl:value-of select="'Oversized'"/>
                            </HandlingCode>
                        </xsl:if>
                    </HandlingCodes>
                    <!-- PATTERN: xsl:for-each with xsl:choose dispatching by element type -->
                    <xsl:for-each select="po:PurchaseOrder/po:ShippingDetails/*[self::po:PackagingInstruction or self::po:HandlingInstruction or self::po:StorageInstruction]">
                        <xsl:choose>
                            <xsl:when test="self::po:PackagingInstruction">
                                <PackagingInstruction>
                                    <xsl:value-of select="."/>
                                </PackagingInstruction>
                            </xsl:when>
                            <xsl:when test="self::po:HandlingInstruction">
                                <HandlingInstruction>
                                    <xsl:value-of select="."/>
                                </HandlingInstruction>
                            </xsl:when>
                            <xsl:when test="self::po:StorageInstruction">
                                <StorageInstruction>
                                    <xsl:value-of select="."/>
                                </StorageInstruction>
                            </xsl:when>
                        </xsl:choose>
                    </xsl:for-each>
                    <xsl:if test="$stockInfoDoc//si:StockInfo/si:InventoryItems/si:PerishableItem">
                        <TemperatureControl>
                            <MinimumTemperature>
                                <xsl:value-of select="$stockInfoDoc//si:StockInfo/si:InventoryItems/si:PerishableItem[1]/si:StorageTemperature/si:MinTemperature"/>
                            </MinimumTemperature>
                            <MaximumTemperature>
                                <xsl:value-of select="$stockInfoDoc//si:StockInfo/si:InventoryItems/si:PerishableItem[1]/si:StorageTemperature/si:MaxTemperature"/>
                            </MaximumTemperature>
                            <TemperatureUnit>
                                <xsl:value-of select="$stockInfoDoc//si:StockInfo/si:InventoryItems/si:PerishableItem[1]/si:StorageTemperature/si:TemperatureUnit"/>
                            </TemperatureUnit>
                        </TemperatureControl>
                    </xsl:if>
                    <xsl:if test="$stockInfoDoc//si:StockInfo/si:InventoryItems/si:HazardousItem">
                        <HazardousMaterials>
                            <UNNumber>
                                <xsl:value-of select="$stockInfoDoc//si:StockInfo/si:InventoryItems/si:HazardousItem[1]/si:UNNumber"/>
                            </UNNumber>
                            <ProperShippingName>
                                <xsl:value-of select="$stockInfoDoc//si:StockInfo/si:InventoryItems/si:HazardousItem[1]/si:ProperShippingName"/>
                            </ProperShippingName>
                            <HazardClass>
                                <xsl:value-of select="$stockInfoDoc//si:StockInfo/si:InventoryItems/si:HazardousItem[1]/si:HazardClass"/>
                            </HazardClass>
                            <xsl:if test="$stockInfoDoc//si:StockInfo/si:InventoryItems/si:HazardousItem[1]/si:PackingGroup">
                                <PackingGroup>
                                    <xsl:value-of select="$stockInfoDoc//si:StockInfo/si:InventoryItems/si:HazardousItem[1]/si:PackingGroup"/>
                                </PackingGroup>
                            </xsl:if>
                        </HazardousMaterials>
                    </xsl:if>
                </SpecialHandling>
            </xsl:if>
            <!-- Cost calculation using BillingInfo tax rate -->
            <ShippingCosts>
                <xsl:variable name="baseRate">
                    <xsl:choose>
                        <xsl:when test="$isExpress">
                            <xsl:value-of select="18.00"/>
                        </xsl:when>
                        <xsl:otherwise>
                            <xsl:value-of select="9.99"/>
                        </xsl:otherwise>
                    </xsl:choose>
                </xsl:variable>
                <xsl:variable name="fuelSurcharge" select="$baseRate * 0.15"/>
                <xsl:variable name="billingCreditRating" select="$billingInfoDoc//bi:BillingInfo/bi:CreditManagement/bi:CreditRating"/>
                <xsl:variable name="insuranceCost" select="if ($totalWeight &gt; 50 or $billingCreditRating = ('C', 'D')) then 25.00 else if ($totalWeight &gt; 20) then 15.00 else 5.00"/>
                <xsl:variable name="billingTaxRate" select="if ($billingInfoDoc//bi:BillingInfo/bi:TaxConfiguration/bi:DefaultTaxRates/bi:TaxRate[1]/bi:Rate) then $billingInfoDoc//bi:BillingInfo/bi:TaxConfiguration/bi:DefaultTaxRates/bi:TaxRate[1]/bi:Rate div 100 else 0.08"/>
                <xsl:variable name="subtotal" select="$baseRate + $fuelSurcharge + $insuranceCost"/>
                <xsl:variable name="taxAmount" select="$subtotal * $billingTaxRate"/>
                <xsl:variable name="total" select="$subtotal + $taxAmount"/>
                <xsl:variable name="billingPaymentTerms" select="$billingInfoDoc//bi:BillingInfo/bi:BillingAccount/bi:PaymentTerms/fin:TermsType"/>
                <BaseShippingCost>
                    <xsl:value-of select="format-number($baseRate, '0.00')"/>
                </BaseShippingCost>
                <!-- PATTERN: Abstract element in sequence (maxOccurs=1) - Concrete substitution group element -->
                <xsl:choose>
                    <xsl:when test="$billingPaymentTerms = 'COD'">
                        <CashPayment>
                            <PaymentMethodCode>
                                <xsl:value-of select="'CASH'"/>
                            </PaymentMethodCode>
                            <PaymentMethodName>
                                <xsl:value-of select="'Cash on Delivery'"/>
                            </PaymentMethodName>
                        </CashPayment>
                    </xsl:when>
                    <xsl:when test="$billingPaymentTerms = 'Net'">
                        <CheckPayment>
                            <PaymentMethodCode>
                                <xsl:value-of select="'CHK'"/>
                            </PaymentMethodCode>
                            <PaymentMethodName>
                                <xsl:value-of select="'Check Payment - Net Terms'"/>
                            </PaymentMethodName>
                            <PayableTo>
                                <xsl:value-of select="'ShipOrder Logistics'"/>
                            </PayableTo>
                        </CheckPayment>
                    </xsl:when>
                    <xsl:when test="$billingPaymentTerms = 'Immediate'">
                        <DigitalWalletPayment>
                            <PaymentMethodCode>
                                <xsl:value-of select="'DW'"/>
                            </PaymentMethodCode>
                            <PaymentMethodName>
                                <xsl:value-of select="'Digital Wallet'"/>
                            </PaymentMethodName>
                            <WalletProvider>
                                <xsl:value-of select="'PayPal'"/>
                            </WalletProvider>
                        </DigitalWalletPayment>
                    </xsl:when>
                    <xsl:otherwise>
                        <CardPayment>
                            <PaymentMethodCode>
                                <xsl:value-of select="'CC'"/>
                            </PaymentMethodCode>
                            <PaymentMethodName>
                                <xsl:value-of select="'Credit Card'"/>
                            </PaymentMethodName>
                            <CardType>
                                <xsl:value-of select="'Visa'"/>
                            </CardType>
                            <Last4Digits>
                                <xsl:value-of select="'0000'"/>
                            </Last4Digits>
                            <CardholderName>
                                <xsl:value-of select="if ($accountHolder/party:PersonName) then concat($accountHolder/party:PersonName/party:FirstName, ' ', $accountHolder/party:PersonName/party:LastName) else 'Card Holder'"/>
                            </CardholderName>
                        </CardPayment>
                    </xsl:otherwise>
                </xsl:choose>
                <Surcharges>
                    <Surcharge>
                        <SurchargeType>
                            <xsl:value-of select="'Fuel'"/>
                        </SurchargeType>
                        <Amount>
                            <xsl:value-of select="format-number($fuelSurcharge, '0.00')"/>
                        </Amount>
                        <Description>
                            <xsl:value-of select="'Standard fuel surcharge based on carrier rate'"/>
                        </Description>
                    </Surcharge>
                    <xsl:if test="po:PurchaseOrder/po:ShippingDetails/po:SignatureRequired = 'true'">
                        <Surcharge>
                            <SurchargeType>
                                <xsl:value-of select="'SignatureRequired'"/>
                            </SurchargeType>
                            <Amount>
                                <xsl:value-of select="'2.50'"/>
                            </Amount>
                            <Description>
                                <xsl:value-of select="'Signature confirmation required on delivery'"/>
                            </Description>
                        </Surcharge>
                    </xsl:if>
                </Surcharges>
                <InsuranceCost>
                    <xsl:value-of select="format-number($insuranceCost, '0.00')"/>
                </InsuranceCost>
                <TaxAmount>
                    <xsl:value-of select="format-number($taxAmount, '0.00')"/>
                </TaxAmount>
                <TotalShippingCost>
                    <xsl:value-of select="format-number($total, '0.00')"/>
                </TotalShippingCost>
            </ShippingCosts>
            <!-- Initial tracking event with TMS load reference -->
            <TrackingInformation>
                <MasterTrackingNumber>
                    <xsl:value-of select="concat('TRK-', format-dateTime(current-dateTime(), '[Y0001][M01][D01]'), '-', substring(po:PurchaseOrder/po:OrderHeader/po:OrderID, 1, 8))"/>
                </MasterTrackingNumber>
                <xsl:if test="$logisticsInfoDoc//li:LogisticsInfo/li:TrackingInformation/li:TrackingURL">
                    <TrackingURL>
                        <xsl:value-of select="$logisticsInfoDoc//li:LogisticsInfo/li:TrackingInformation/li:TrackingURL"/>
                    </TrackingURL>
                </xsl:if>
                <TrackingEvents>
                    <TrackingEvent>
                        <EventDateTime>
                            <xsl:value-of select="current-dateTime()"/>
                        </EventDateTime>
                        <EventType>
                            <xsl:value-of select="'Created'"/>
                        </EventType>
                        <EventDescription>
                            <xsl:value-of select="concat('Order created. TMS Load: LOAD-', format-dateTime(current-dateTime(), '[Y0001][M01][D01]'))"/>
                        </EventDescription>
                    </TrackingEvent>
                </TrackingEvents>
                <CurrentLocation>
                    <City>
                        <xsl:value-of select="if ($stockInfoDoc//si:StockInfo/si:WarehouseLocations/si:Warehouse[1]/si:WarehouseName) then $stockInfoDoc//si:StockInfo/si:WarehouseLocations/si:Warehouse[1]/si:WarehouseName else 'Distribution Center'"/>
                    </City>
                    <StateProvince>
                        <xsl:value-of select="'CA'"/>
                    </StateProvince>
                    <Country>
                        <xsl:value-of select="'USA'"/>
                    </Country>
                </CurrentLocation>
                <EstimatedDelivery>
                    <xsl:value-of select="current-dateTime() + xs:dayTimeDuration(concat('P', $daysToAdd, 'D'))"/>
                </EstimatedDelivery>
            </TrackingInformation>
            <!-- International customs with BillingInfo invoice -->
            <xsl:if test="$isInternational">
                <CustomsInformation>
                    <CustomsDeclaration>
                        <ExportReason>
                            <xsl:value-of select="'Sale'"/>
                        </ExportReason>
                        <DutyPayment>
                            <xsl:value-of select="'Sender'"/>
                        </DutyPayment>
                        <CustomsValue>
                            <xsl:value-of select="format-number($totalValue, '0.00')"/>
                        </CustomsValue>
                    </CustomsDeclaration>
                    <xsl:choose>
                        <xsl:when test="$totalWeight &gt; 50">
                            <Pallet>
                                <ContainerID>
                                    <xsl:value-of select="concat('CUST-PLT-', format-dateTime(current-dateTime(), '[Y0001][M01][D01]'))"/>
                                </ContainerID>
                                <ContainerDescription>
                                    <xsl:value-of select="'Customs pallet for heavy international shipment'"/>
                                </ContainerDescription>
                                <Dimensions>
                                    <xsl:attribute name="unit">
                                        <xsl:value-of select="'Inches'"/>
                                    </xsl:attribute>
                                    <Length>
                                        <xsl:value-of select="48"/>
                                    </Length>
                                    <Width>
                                        <xsl:value-of select="40"/>
                                    </Width>
                                    <Height>
                                        <xsl:value-of select="6"/>
                                    </Height>
                                </Dimensions>
                                <MaxWeight>
                                    <xsl:value-of select="2000"/>
                                </MaxWeight>
                                <PalletSize>
                                    <xsl:value-of select="'Standard48x40'"/>
                                </PalletSize>
                            </Pallet>
                        </xsl:when>
                        <xsl:otherwise>
                            <StandardBox>
                                <ContainerID>
                                    <xsl:value-of select="concat('CUST-BOX-', format-dateTime(current-dateTime(), '[Y0001][M01][D01]'))"/>
                                </ContainerID>
                                <ContainerDescription>
                                    <xsl:value-of select="'Standard box for international customs'"/>
                                </ContainerDescription>
                                <Dimensions>
                                    <xsl:attribute name="unit">
                                        <xsl:value-of select="'Inches'"/>
                                    </xsl:attribute>
                                    <Length>
                                        <xsl:value-of select="12"/>
                                    </Length>
                                    <Width>
                                        <xsl:value-of select="10"/>
                                    </Width>
                                    <Height>
                                        <xsl:value-of select="8"/>
                                    </Height>
                                </Dimensions>
                                <MaxWeight>
                                    <xsl:value-of select="50"/>
                                </MaxWeight>
                                <BoxStrength>
                                    <xsl:value-of select="'DoubleWall'"/>
                                </BoxStrength>
                            </StandardBox>
                        </xsl:otherwise>
                    </xsl:choose>
                    <CommercialInvoice>
                        <InvoiceNumber>
                            <xsl:value-of select="$billingInfoDoc//bi:BillingInfo/bi:Invoices/bi:StandardInvoice[1]/bi:InvoiceID"/>
                        </InvoiceNumber>
                        <InvoiceDate>
                            <xsl:value-of select="format-date(current-date(), '[Y0001]-[M01]-[D01]')"/>
                        </InvoiceDate>
                        <TermsOfSale>
                            <xsl:value-of select="'FOB'"/>
                        </TermsOfSale>
                    </CommercialInvoice>
                </CustomsInformation>
            </xsl:if>
            <!-- Warehouse assignment from StockInfo -->
            <FulfillmentTracking>
                <FulfillmentStatus>
                    <xsl:value-of select="'Pending'"/>
                </FulfillmentStatus>
                <WarehouseLocation>
                    <xsl:value-of select="if ($stockInfoDoc//si:StockInfo/si:WarehouseLocations/si:Warehouse[1]/si:WarehouseName) then $stockInfoDoc//si:StockInfo/si:WarehouseLocations/si:Warehouse[1]/si:WarehouseName else 'Main Warehouse'"/>
                </WarehouseLocation>
                <FulfillmentEvents>
                    <FulfillmentEvent>
                        <EventDateTime>
                            <xsl:value-of select="current-dateTime()"/>
                        </EventDateTime>
                        <EventType>
                            <xsl:value-of select="'Pending'"/>
                        </EventType>
                        <EventDescription>
                            <xsl:value-of select="concat('Order received. WMS Wave: WAVE-', format-dateTime(current-dateTime(), '[Y0001][M01][D01]-[H01]'))"/>
                        </EventDescription>
                        <xsl:if test="$stockInfoDoc//si:StockInfo/si:WarehouseLocations/si:Warehouse[1]/si:WarehouseManager">
                            <PerformedBy>
                                <xsl:value-of select="$stockInfoDoc//si:StockInfo/si:WarehouseLocations/si:Warehouse[1]/si:WarehouseManager"/>
                            </PerformedBy>
                        </xsl:if>
                    </FulfillmentEvent>
                </FulfillmentEvents>
            </FulfillmentTracking>
        </ShipOrder>
    </xsl:template>
</xsl:stylesheet>
