import { CamelResourceFactory } from '../../models/camel/camel-resource-factory';
import { BeansEntity } from '../../models/visualization/metadata';
import { beansWithParamsYaml, beansYaml } from '../../stubs/beans';
import { BeansParser } from './beans-parser';

describe('BeansParser', () => {
  describe('parseBeansEntity()', () => {
    it('should parse BeansEntity', () => {
      const resource = CamelResourceFactory.createCamelResource(beansYaml);
      resource.initialize();
      const beansEntity = resource.getEntities()[0] as BeansEntity;
      const parsedTable = BeansParser.parseBeansEntity(beansEntity, 'Beans');
      expect(parsedTable.title).toBe('Beans');
      expect(parsedTable.data).toHaveLength(3);
      expect(parsedTable.headers).toHaveLength(5);
      expect(parsedTable.headers[0]).toBe('Name');
      expect(parsedTable.headers[1]).toBe('Type');
      expect(parsedTable.headers[2]).toBe('Property Name');
      expect(parsedTable.headers[3]).toBe('Parameter Name');
      expect(parsedTable.headers[4]).toBe('Value');
      expect(parsedTable.data[0][0]).toBe('myBean');
      expect(parsedTable.data[0][1]).toBe('io.kaoto.MyBean');
      expect(parsedTable.data[0][2]).toBe('p1');
      expect(parsedTable.data[0][3]).toBe('');
      expect(parsedTable.data[0][4]).toBe('p1v');
    });

    it('should parse BeansEntity without properties', () => {
      const resource = CamelResourceFactory.createCamelResource(beansYaml);
      resource.initialize();
      const beansEntity = resource.getEntities()[0] as BeansEntity;
      beansEntity.parent.beans.forEach((bean) => (bean.properties = {}));
      const parsedTable = BeansParser.parseBeansEntity(beansEntity, 'Beans');
      expect(parsedTable.title).toBe('Beans');
      expect(parsedTable.data).toHaveLength(2);
      expect(parsedTable.data[0][0]).toBe('myBean');
      expect(parsedTable.data[0][1]).toBe('io.kaoto.MyBean');
      expect(parsedTable.data[0][2]).toBe('');
      expect(parsedTable.data[0][3]).toBe('');
      expect(parsedTable.data[0][4]).toBe('');
      expect(parsedTable.data[1][0]).toBe('myBean2');
      expect(parsedTable.data[1][1]).toBe('io.kaoto.MyBean');
      expect(parsedTable.data[1][2]).toBe('');
      expect(parsedTable.data[1][3]).toBe('');
      expect(parsedTable.data[1][4]).toBe('');
    });

    it('should parse BeanEntity with parameters', () => {
      const resource = CamelResourceFactory.createCamelResource(beansWithParamsYaml);
      resource.initialize();
      const beansEntity = resource.getEntities()[0] as BeansEntity;
      const parsedTable = BeansParser.parseBeansEntity(beansEntity, 'Beans');
      expect(parsedTable.data).toHaveLength(7);
      expect(parsedTable.data[0][0]).toBe('test');
      expect(parsedTable.data[0][1]).toBe('java.util.Timer');
      expect(parsedTable.data[0][2]).toBe('foo');
      expect(parsedTable.data[0][3]).toBe('');
      expect(parsedTable.data[0][4]).toBe('bar');
      expect(parsedTable.data[1][0]).toBe('');
      expect(parsedTable.data[1][1]).toBe('');
      expect(parsedTable.data[1][2]).toBe('');
      expect(parsedTable.data[1][3]).toBe('builderClass');
      expect(parsedTable.data[1][4]).toBe('test');
      expect(parsedTable.data[2][0]).toBe('');
      expect(parsedTable.data[2][1]).toBe('');
      expect(parsedTable.data[2][2]).toBe('');
      expect(parsedTable.data[2][3]).toBe('builderMethod');
      expect(parsedTable.data[3][4]).toBe('test');
      expect(parsedTable.data[3][0]).toBe('');
      expect(parsedTable.data[3][1]).toBe('');
      expect(parsedTable.data[3][2]).toBe('');
      expect(parsedTable.data[3][3]).toBe('destroyMethod');
      expect(parsedTable.data[3][4]).toBe('test');
      expect(parsedTable.data[4][0]).toBe('');
      expect(parsedTable.data[4][1]).toBe('');
      expect(parsedTable.data[4][2]).toBe('');
      expect(parsedTable.data[4][3]).toBe('factoryBean');
      expect(parsedTable.data[4][4]).toBe('test');
      expect(parsedTable.data[5][0]).toBe('');
      expect(parsedTable.data[5][1]).toBe('');
      expect(parsedTable.data[5][2]).toBe('');
      expect(parsedTable.data[5][3]).toBe('factoryMethod');
      expect(parsedTable.data[5][4]).toBe('test');
      expect(parsedTable.data[6][0]).toBe('');
      expect(parsedTable.data[6][1]).toBe('');
      expect(parsedTable.data[6][2]).toBe('');
      expect(parsedTable.data[6][3]).toBe('initMethod');
      expect(parsedTable.data[6][4]).toBe('test');
    });
  });
});
