name: 📦 Build npm Package
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@kaoto'
          cache: 'yarn'

      # Install dependencies
      - run: yarn

      # Lint files
      - name: 💅 Run eslint
        run: yarn workspaces foreach --verbose --all --topological-dev run lint

      # Lint style files
      - name: 💅 Run stylelint
        run: yarn workspace @kaoto/kaoto run lint:style

      # Build packages excluding @kaoto/camel-catalog since it was build during installing dependencies
      - name: Build packages
        run: yarn workspaces foreach --verbose --all --topological-dev  run build

      # Run tests
      - name: 🧪 Run tests
        run: yarn workspaces foreach --verbose --all --topological-dev run test

      - name: Upload results to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      # Build lib
      - name: Build @kaoto/kaoto package in lib mode
        run: yarn workspace @kaoto/kaoto run build:lib
