name: 📦 Build npm Package
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@kaoto'
          cache: 'yarn'


      # Install dependencies
      - run: yarn

      # Lint files
      - name: 💅 Run eslint
        run: yarn workspaces foreach --verbose --all --topological-dev run lint

      # Lint style files
      - name: 💅 Run stylelint
        run: yarn workspace @kaoto/kaoto run lint:style

      # Build packages excluding @kaoto/camel-catalog since it was build during installing dependencies
      - name: Build packages
        run: yarn workspaces foreach --verbose --all --topological-dev  run build

      # Run tests
      - name: 🧪 Run tests
        run: yarn workspaces foreach --verbose --all --topological-dev run test

      - name: Upload results to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      # Build lib
      - name: Build @kaoto/kaoto package in lib mode
        run: yarn workspace @kaoto/kaoto run build:lib
