name: 📦 Build npm Package
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@kaoto'
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Install dependencies
      - run: yarn

      # Build each package of the monorepo, in topological order, meaning, dependencies first
      - run: yarn workspaces foreach --topological-dev --verbose run build

      # Build @kaoto-next/ui package in lib mode
      - run: yarn workspace @kaoto-next/ui run build:lib
