name: 🏗️ E2E Weekly Tests (Cypress)

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  install:
    runs-on: ubuntu-latest

    container:
      image: cypress/browsers:node-24.17.0-chrome-149.0.7827.155-1-ff-152.0-edge-149.0.4022.69-1
      options: --user 1001

    steps:
      - name: 👷‍♀️ Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # Install dependencies
      - name: 🔧 Install dependencies
        run: yarn install --immutable --mode=skip-build

      # Build packages excluding @kaoto/camel-catalog since it was build during installing dependencies
      - name: Build packages
        run: yarn workspaces foreach --verbose --all --topological-dev  run build:dev

      # Build lib
      - name: Build @kaoto/kaoto package in lib mode
        run: yarn workspace @kaoto/kaoto run build:lib

      - name: 💾 Save build folder
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ui-dist
          if-no-files-found: error
          path: packages/ui/dist

  test-on-firefox:
    needs: install
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-24.17.0-chrome-149.0.7827.155-1-ff-152.0-edge-149.0.4022.69-1
      options: --user 1001

    steps:
      - name: 👷‍♀️ Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: 🗄️ Download the UI build folder
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ui-dist
          path: packages/ui/dist

      - name: 🔨 Cypress run
        uses: cypress-io/github-action@fa4a118725a8f001170d49631ea89e5d66fee626 # v7.4.1
        with:
          browser: firefox
          # we have already installed all dependencies above
          # install: false
          start: yarn workspace @kaoto/kaoto run preview --host
          config: baseUrl=http://localhost:4173
          working-directory: packages/ui-tests
          wait-on: 'http://127.0.0.1:4173'
          wait-on-timeout: 120
          env: grepTags=weekly
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 💾 Save videos
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: videos-firefox
          path: packages/ui-tests/cypress/videos

      - name: 💾 Save screenshots
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: screenshots-firefox
          path: packages/ui-tests/cypress/screenshots

  test-on-chrome:
    needs: install
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-24.17.0-chrome-149.0.7827.155-1-ff-152.0-edge-149.0.4022.69-1
      options: --user 1001

    steps:
      - name: 👷‍♀️ Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: 🗄️ Download the UI build folder
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ui-dist
          path: packages/ui/dist

      - name: 🔨 Cypress run
        uses: cypress-io/github-action@fa4a118725a8f001170d49631ea89e5d66fee626 # v7.4.1
        with:
          browser: chrome
          # we have already installed all dependencies above
          # install: false
          start: yarn workspace @kaoto/kaoto run preview --host
          config: baseUrl=http://localhost:4173
          working-directory: packages/ui-tests
          wait-on: 'http://127.0.0.1:4173'
          wait-on-timeout: 120
          env: grepTags=weekly
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 💾 Save videos
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: videos-chrome
          path: packages/ui-tests/cypress/videos

      - name: 💾 Save screenshots
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: screenshots-chrome
          path: packages/ui-tests/cypress/screenshots

  test-on-edge:
    needs: install
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-24.17.0-chrome-149.0.7827.155-1-ff-152.0-edge-149.0.4022.69-1
      options: --user 1001

    steps:
      - name: 👷‍♀️ Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: 🗄️ Download the UI build folder
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ui-dist
          path: packages/ui/dist

      - name: 🔨 Cypress run
        uses: cypress-io/github-action@fa4a118725a8f001170d49631ea89e5d66fee626 # v7.4.1
        with:
          browser: edge
          # we have already installed all dependencies above
          # install: false
          start: yarn workspace @kaoto/kaoto run preview --host
          config: baseUrl=http://localhost:4173
          working-directory: packages/ui-tests
          wait-on: 'http://127.0.0.1:4173'
          wait-on-timeout: 120
          env: grepTags=weekly
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 💾 Save videos
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: videos-edge
          path: packages/ui-tests/cypress/videos

      - name: 💾 Save screenshots
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: screenshots-edge
          path: packages/ui-tests/cypress/screenshots
