name: 🏗️ E2E Tests (Cypress)

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  install:
    runs-on: ubuntu-latest

    container:
      image: cypress/browsers:node-24.17.0-chrome-149.0.7827.155-1-ff-152.0-edge-149.0.4022.69-1
      options: --user 1001

    steps:
      - name: 👷‍♀️ Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: actions/cache@v6
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # Install dependencies
      - run: yarn install --immutable

      - name: Build packages
        run: yarn workspace @kaoto/kaoto run build:dev

      # Build lib
      - name: Build @kaoto/kaoto package in lib mode
        run: yarn workspace @kaoto/kaoto run build:lib

      - name: 💾 Save build folder
        uses: actions/upload-artifact@v7
        with:
          name: ui-dist
          if-no-files-found: error
          path: packages/ui/dist

  test-on-firefox:
    needs: install
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-24.17.0-chrome-149.0.7827.155-1-ff-152.0-edge-149.0.4022.69-1
      options: --user 1001
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4]
    steps:
      - name: 👷‍♀️ Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: 🗄️ Download the UI build folder
        uses: actions/download-artifact@v8
        with:
          name: ui-dist
          path: packages/ui/dist

      - name: 🔨 Cypress run
        uses: cypress-io/github-action@v7
        with:
          browser: firefox
          # we have already installed all dependencies above
          # install: false
          start: yarn workspace @kaoto/kaoto run preview --host
          config: baseUrl=http://localhost:4173
          working-directory: packages/ui-tests
          wait-on: 'http://127.0.0.1:4173'
          wait-on-timeout: 120
          env: grepTags=-weekly
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}

      - name: 💾 Save videos
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: videos-firefox-${{ matrix.containers }}
          path: packages/ui-tests/cypress/videos

      - name: 💾 Save screenshots
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: screenshots-firefox-${{ matrix.containers }}
          path: packages/ui-tests/cypress/screenshots

  test-on-chrome:
    needs: install
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-24.17.0-chrome-149.0.7827.155-1-ff-152.0-edge-149.0.4022.69-1
      options: --user 1001
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4]

    steps:
      - name: 👷‍♀️ Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: 🗄️ Download the UI build folder
        uses: actions/download-artifact@v8
        with:
          name: ui-dist
          path: packages/ui/dist

      - name: 🔨 Cypress run
        uses: cypress-io/github-action@v7
        with:
          browser: chrome
          # we have already installed all dependencies above
          # install: false
          start: yarn workspace @kaoto/kaoto run preview --host
          config: baseUrl=http://localhost:4173
          working-directory: packages/ui-tests
          wait-on: 'http://127.0.0.1:4173'
          wait-on-timeout: 120
          env: grepTags=-weekly
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}

      - name: 💾 Save videos
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: videos-chrome-${{ matrix.containers }}
          path: packages/ui-tests/cypress/videos

      - name: 💾 Save screenshots
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: screenshots-chrome-${{ matrix.containers }}
          path: packages/ui-tests/cypress/screenshots

  test-on-edge:
    needs: install
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-24.17.0-chrome-149.0.7827.155-1-ff-152.0-edge-149.0.4022.69-1
      options: --user 1001
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4]
    steps:
      - name: 👷‍♀️ Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: 🗄️ Download the UI build folder
        uses: actions/download-artifact@v8
        with:
          name: ui-dist
          path: packages/ui/dist

      - name: 🔨 Cypress run
        uses: cypress-io/github-action@v7
        with:
          browser: edge
          # we have already installed all dependencies above
          # install: false
          start: yarn workspace @kaoto/kaoto run preview --host
          config: baseUrl=http://localhost:4173
          working-directory: packages/ui-tests
          wait-on: 'http://127.0.0.1:4173'
          wait-on-timeout: 120
          env: grepTags=-weekly
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
      - name: 💾 Save videos
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: videos-edge-${{ matrix.containers }}
          path: packages/ui-tests/cypress/videos

      - name: 💾 Save screenshots
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: screenshots-edge-${{ matrix.containers }}
          path: packages/ui-tests/cypress/screenshots
