name: 🏗️ E2E Weekly Tests (Cypress)

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  install:
    runs-on: ubuntu-latest

    container:
      image: cypress/browsers:node-24.17.0-chrome-149.0.7827.155-1-ff-152.0-edge-149.0.4022.69-1@sha256:d053d6ed0c096ec30762085c99ac5be617b1c0f5ee83779930a42b377e809f83
      options: --user 1001

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: 👷‍♀️ Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # Install dependencies
      - run: yarn install --immutable

      # Build packages excluding @kaoto/camel-catalog since it was build during installing dependencies
      - name: Build packages
        run: yarn workspaces foreach --verbose --all --topological-dev  run build:dev

      # Build lib
      - name: Build @kaoto/kaoto package in lib mode
        run: yarn workspace @kaoto/kaoto run build:lib

      - name: 💾 Save build folder
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: ui-dist
          if-no-files-found: error
          path: packages/ui/dist


  test-on-firefox:
    needs: install
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-24.17.0-chrome-149.0.7827.155-1-ff-152.0-edge-149.0.4022.69-1@sha256:d053d6ed0c096ec30762085c99ac5be617b1c0f5ee83779930a42b377e809f83
      options: --user 1001

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: 👷‍♀️ Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false

      - name: 🗄️ Download the UI build folder
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
        with:
          name: ui-dist
          path: packages/ui/dist

      - name: 🔨 Cypress run
        uses: cypress-io/github-action@2ad32e649e4db26c07674ebae31a297601dbcbaf
        with:
          browser: firefox
          # we have already installed all dependencies above
          # install: false
          start: yarn workspace @kaoto/kaoto run preview --host
          config: baseUrl=http://localhost:4173
          working-directory: packages/ui-tests
          wait-on: 'http://127.0.0.1:4173'
          wait-on-timeout: 120
          env: grepTags=weekly
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 💾 Save videos
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: videos-firefox
          path: packages/ui-tests/cypress/videos

      - name: 💾 Save screenshots
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: screenshots-firefox
          path: packages/ui-tests/cypress/screenshots

  test-on-chrome:
    needs: install
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-24.17.0-chrome-149.0.7827.155-1-ff-152.0-edge-149.0.4022.69-1@sha256:d053d6ed0c096ec30762085c99ac5be617b1c0f5ee83779930a42b377e809f83
      options: --user 1001

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: 👷‍♀️ Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false

      - name: 🗄️ Download the UI build folder
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
        with:
          name: ui-dist
          path: packages/ui/dist

      - name: 🔨 Cypress run
        uses: cypress-io/github-action@2ad32e649e4db26c07674ebae31a297601dbcbaf
        with:
          browser: chrome
          # we have already installed all dependencies above
          # install: false
          start: yarn workspace @kaoto/kaoto run preview --host
          config: baseUrl=http://localhost:4173
          working-directory: packages/ui-tests
          wait-on: 'http://127.0.0.1:4173'
          wait-on-timeout: 120
          env: grepTags=weekly
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 💾 Save videos
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: videos-chrome
          path: packages/ui-tests/cypress/videos

      - name: 💾 Save screenshots
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: screenshots-chrome
          path: packages/ui-tests/cypress/screenshots

  test-on-edge:
    needs: install
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-24.17.0-chrome-149.0.7827.155-1-ff-152.0-edge-149.0.4022.69-1@sha256:d053d6ed0c096ec30762085c99ac5be617b1c0f5ee83779930a42b377e809f83
      options: --user 1001

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: 👷‍♀️ Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false

      - name: 🗄️ Download the UI build folder
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
        with:
          name: ui-dist
          path: packages/ui/dist

      - name: 🔨 Cypress run
        uses: cypress-io/github-action@2ad32e649e4db26c07674ebae31a297601dbcbaf
        with:
          browser: edge
          # we have already installed all dependencies above
          # install: false
          start: yarn workspace @kaoto/kaoto run preview --host
          config: baseUrl=http://localhost:4173
          working-directory: packages/ui-tests
          wait-on: 'http://127.0.0.1:4173'
          wait-on-timeout: 120
          env: grepTags=weekly
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 💾 Save videos
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: videos-edge
          path: packages/ui-tests/cypress/videos

      - name: 💾 Save screenshots
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: screenshots-edge
          path: packages/ui-tests/cypress/screenshots
