name: 🏗️ VS Code Kaoto Tests

on:
  push:
    branches:
      - main

jobs:
  trigger-vscode-tests:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Trigger vscode-kaoto tests
        uses: convictional/trigger-workflow-and-wait@f69fa9eedd3c62a599220f4d5745230e237904be
        with:
          owner: KaotoIO
          repo: vscode-kaoto
          ref: main
          github_token: ${{ secrets.KAOTO_CI_TOKEN }}
          workflow_file_name: main-kaoto.yaml
          propagate_failure: false # do not fail this pipeline when vscode-kaoto tests fails
          wait_workflow: false # do not wait for vscode-kaoto tests finish
